export declare enum RideStatus {
    REQUESTED = "REQUESTED",
    MATCHING = "MATCHING",
    DRIVER_ASSIGNED = "DRIVER_ASSIGNED",
    DRIVER_ARRIVING = "DRIVER_ARRIVING",
    DRIVER_ARRIVED = "DRIVER_ARRIVED",
    RIDE_STARTED = "RIDE_STARTED",
    COMPLETED = "COMPLETED",
    PAYMENT_PENDING = "PAYMENT_PENDING",
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED",
    CANCELLED = "CANCELLED",
    FAILED = "FAILED"
}
//# sourceMappingURL=ride-status.enum.d.ts.map